### ISSUE TITLE
Migrate all our CI code to dagger

### ISSUE THREAD

**Issue by samalba** [dagger/dagger#1549]
This is a master issue to track all the work related to migrating our CI.

### Goal

Port all binary builds, github workflows, Makefile, integration tests, website and docs deployment to a single dagger plan.

Extra context: https://github.com/dagger/dagger/discussions/1230

_(NOTE: a single dagger plan is to reflect the intent to fit in a single DAG, can be revisited if it works)_

### Todo list (non-exhautive, unordered)

- [ ] ~~Define the base UX to selectively run certain parts of the Plan using params~~
- [x] #1522
- [x] #1556 
- [x] Port universe `go` package
- [x] Create a `cue` package
- [x] Migrate universe integration tests (in progress #2442)
- [ ] ~~Convert our Github workflows~~
- [x] #1020

**Comment by mircubed** [comment]
@samalba please update

**Comment by jpadams** [comment]
related #2434

**Comment by samalba** [comment]
> @samalba please update

updated!

**Comment by mircubed** [comment]
@samalba will open a new issue to cover GitHub workflows, so this will be broken into two issues.

**Comment by samalba** [comment]
I reviewed all the workflows, all relevant github workflows are currently using the dagger action and a dagger plan. The rest don't need to be migrated.

Less urgent, we'll need to investigate to find a way to either:

A/ Dispatch all `dagger do` to separate workflows so we take advantage of github parallelization and events

OR

B/ Run all the dagger-do into a single workflow and efficiently use buildkit's cache so we run only what needs to run on every change
