### ISSUE TITLE
`core.#Start` follow-ups and enhancements

### ISSUE THREAD

**Issue by sipsma** [dagger/dagger#2398]
# Task List
Things we need to make `core.#Start` tasks basically useful:

Basic quick fixes:
- [x] [Ability to stop gracefully](https://github.com/dagger/dagger/pull/2460)
- [ ] [Stdout/stderr of the process are logged in the same way as normal `core.#Exec` ](https://github.com/dagger/dagger/issues/2469)

Networking:
- [ ] [Clean way of connecting from a client in an `#Exec` to a service in `#Start`](https://github.com/dagger/dagger/issues/2389)
- [ ] [Client-side proxying](https://github.com/dagger/dagger/issues/1258)

Cue:
- [ ] [Explicit Dependencies](https://github.com/dagger/dagger/issues/940)

Buildkit fixes:
- [ ] [Cleanup containers automatically if client disconnects](https://github.com/moby/buildkit/issues/2811) 

And, once we have the above features, we can document:
- [ ] [User guides and Documentation](https://github.com/dagger/dagger/issues/2397)

Misc (not necessary for documentation but shouldn't lose track of):
- [ ] Support for output in TTY mode (right now the logs are only visible in plain progress mode, as mentioned [here](https://github.com/dagger/dagger/pull/2561#issuecomment-1147905745))

In parallel, we should gather both current feedback and feedback on the updated features: 
- [ ] [Feedback Tracker](https://github.com/dagger/dagger/issues/2489)

# Latest Updates
* **Previously**
   * Added the initial barebones implementation
   * Sent out PR for supporting graceful stops [here](https://github.com/dagger/dagger/pull/2460)
   * Wrote code for getting stdout/stderr of process plugged into our logging system. It is based on the graceful stop PR, so I am waiting to send it out, but branch is [here](https://github.com/sipsma/dagger/commit/15ee294976ca41191f425391daca21cb9fb466d4)
   * Merged graecful stop PR
* **Right Now**
   * Getting [core.Start output log PR](https://github.com/dagger/dagger/pull/2561) merged
* **Next Steps**
   * Fix the buildkit bug upstream
   * TBD based on conversation with team, but networking feature may be a good next follow-up.

# Discussion
`core.#Start` and related tasks enables users to run ephemeral containers and "sidecar" services that assist the execution of other tasks in an action or provide interactive services to end users. Whereas a `core.#Exec` is used to run synchronous commands with cache-able outputs, such as building code or executing a test, a `core.#Start` has no FS output consumable by other tasks and is not cache-able. The tradeoff of those limitations is that it can be used in ways that are off-limits to `core.#Exec` due to non-determinism (such as interaction with the client or providing network services).

Example use cases:
1. Running a database used by tests executing in other `core.#Exec` tasks.
2. Development servers (i.e. a server for a web project built by dagger, accessible over the user's localhost)
3. Interactive processes, such as [debug shells](https://github.com/dagger/dagger/issues/2197) or dev environments
4. Running tracing daemons like Jaeger (both for user tasks and even Buildkit itself)

## Issues
A few of the tasks are just basic usability concerns ([graceful stops](https://github.com/dagger/dagger/pull/2460) and [stdout/stderr logging](https://github.com/dagger/dagger/issues/2469)) or [bug fixes upstream](https://github.com/moby/buildkit/issues/2811). The others are more involved and touch on more components.

### Networking
Once a process has been started in a `core.#Start`, we need a way of actually interacting with it. Today, this is possible but far from ideal:
1. The network can be used, but because all Buildkit containers are in the same host network namespace (at least in our default buildkitd, [as mentioned here](https://github.com/dagger/dagger/issues/1258#issuecomment-1117592178)), it's easy for port contention to become a problem. Additionally, this requires just hardcoding ports and addresses on both the client and server, which is not very flexible and can be host-dependent.
1. A unix socket can be shared over a cache mount. This is a bit of an abuse of a cache mount though and is quite delicate. For example, it doesn't work if one of the containers specifies `always: true`.

Users instead need [the ability to easily expose network services between containers](https://github.com/dagger/dagger/issues/2389) (conceptually similar to docker compose) and [the ability to proxy connections from the dagger client to services in a `core.#Start`](https://github.com/dagger/dagger/issues/1258).

### Cue
`core.#Start` is asynchronous, so it's quite important to be able to create dependencies on it having started before executing other tasks. E.g. a test that uses a database running in a `core.#Start` needs to be sure that the database has been started before running.

Right now, this can only be easily accomplished using [tricks like the one here](https://github.com/dagger/dagger/blob/35390b02d7e0ac54db31614bb1ef16c6ddb46d6f/tests/tasks/exec/start_stop_exec.cue#L42), which don't always work (that trick only works when creating a dependency between two core tasks).

Instead, users need the ability to flexibly create arbitrary dependencies between [any cue structs](https://github.com/dagger/dagger/issues/940).

**Comment by mircubed** [comment]
@sipsma hi! I just assigned to you for tracking, but I will set up some time for us to go through this epic in detail

**Comment by sipsma** [comment]
Sounds good, thanks @mircubed!

**Comment by shykes** [comment]
Closing since CUE APIs are frozen, and this design work continues in the GraphQL API now.
