### ISSUE TITLE
Universe contributions change (alpha, beta, stable) tracking issue

### ISSUE THREAD

**Issue by jpadams** [dagger/dagger#2634]
We've changed the contribution flow and need to let folks know about it in all the right places (plus help with automation):
https://github.com/dagger/dagger/discussions/2616

TODO:
- [ ] https://github.com/dagger/dagger/issues/2633
- [ ] https://github.com/dagger/dagger/issues/2637
- [x] https://github.com/dagger/dagger/issues/2635
- [x] https://github.com/dagger/dagger/pull/2617

Related:
- [ ] https://github.com/dagger/dagger/issues/2636
