### ISSUE TITLE
docs: July checkin on CI docs

### ISSUE THREAD

**Issue by jpadams** [dagger/dagger#2843]
- [X] Pass through CI discussion to ask/answer some questions - https://github.com/dagger/dagger/discussions/1677

[CI Docs](https://docs.dagger.io/1201/ci-environment/)
- [x] CircleCI - adding simple example, https://github.com/dagger/dagger/pull/2841 - more to come: https://github.com/dagger/dagger/issues/2842
- [x] TravisCI - updating YAML title and removing `---` - https://github.com/dagger/dagger/pull/2844
- [X] GitLab - updated example, used wget for simplification - https://github.com/dagger/dagger/pull/2828
- [X] GitLab - added title for file name - https://github.com/dagger/dagger/pull/2845
- [x] Tekton - Added appropriate title for file name - https://github.com/dagger/dagger/pull/2846
