### ISSUE TITLE
[EPIC] Go SDK Doc Launch Plan 

### ISSUE THREAD

**Issue by mircubed** [dagger/dagger#3360]
Docs Title:  Go SDK for Dagger  
Note - it needs to have a tech preview banner

**Sidebar plan:** 
- Introduction 
- Install page 
- Go Getting Started
- API Reference
- FAQ

**URL plan and where it lives:** 
Build in the current site - @vikram-dagger I'll let you create an issue for this since I am not sure if we just need a PR instead of an issue. 

**What pages do we need for launch:** 
- [ ] Introduction #3361  - use this content and tweak to focus on SDK theme - https://github.com/dagger/dagger/tree/cloak
@shykes  will provide guidance and reviews here when needed 
- [ ] Installation page #3362 - Make sure it has min. version requirements 
- [ ] Go getting started guide #3363 - Make sure to include install instructions for Go SDK (point to install page above) 
@kpenfound  help support Vikram here 
- [ ] FAQ #3177  (Vikram’s questions and we will expand later) 
Must have a “what’s up with CUE?” question - asked @shykes  to add the content for that one. 
- [ ] Go SKD reference page #3364 - Just link to Go generated docs 
@vito  will lead proposal, but @vikram-dagger will implement. We will look into hosting ourselves later (#3365).

**User experience summary:** 
This is the experience that we are targeting for launch. 

**Scenario 1-** 

- Sees banner about blog post on website or social 
- Clicks docs link in blog post 
- Goes to Go SDK docs 

**Scenario 2 -** 

- Clicks docs tab on homepage 
- Taken to old version docs, but sees a CTA to check out the new Go SDK (Miranda create a proposal issue) 
- Clicks SDK CTA and goes to Go docs with no backtracking option to see old docs 

**Additional issues to do to achieve user experience:**  
- [ ] Need pointer to go sdk docs from main docs since it won’t automatically show the new docs when they click docs #3366

**Timeline:** 
- Monday - review PR 
- Tuesday - go/no go decision made 
- Wednesday - merge PR 
- Thursday - launch if PR merges
