### ISSUE TITLE
Ship SDK-aware docs

### ISSUE THREAD

**Issue by mircubed** [dagger/dagger#3440]
## Overview

This issue tracks the work required to ship a new documentation site for Dagger, that is *SDK-aware*:

* Explains Dagger as an engine which can be programmed via different SDKs
* Incorporate docs for CUE SDK (rebranding of the "classic" dagger 0.2)
* Incorporate docs for Go SDK
* Allow for easy addition of more SDK docs in the coming weeks

Other requirements include:

* No broken URLs if possible
* Minimize tooling and maintenance complication

## Completion

This issue is complete when the new SDK-aware docs are **shipped** to devel.docs.dagger.io:
* Any Go developer can, if given the URL, access the Go SDK Docs somewhere under https://devel.docs.dagger.io
* Using the docs at that URL, and no other information, a Go developer can successfully develop and run their first Dagger pipeline in Go

**THIS ISSUE DOES NOT TRACK LAUNCHING**: do not include work that changes the contents of https://dagger.io

## PR tracker

PRs in flight:

* #3450
* #3451
* #3452 
* https://github.com/dagger/dagger/pull/3454

## Task list

**Create new docs sites -** 
- [x] Vikram will create the structure of the new doc plan above as a single PR for review. We will add pages once the PR is approved 

Dagger Overview page on the main docs site - 
- [x] Solomon owns the introduction 

**Go SDK Site -** 
- [ ] @kpenfound  will work on Getting started guide updates 
- [ ] Vikram will move over the current docs to new site 

**CUE SDK site -** 
- [ ] @jpadams  will help migrate old Dagger docs in the new CUE SDK docs site 
- [ ] NEED OWNER to choose and change the Dagger binary name
- [ ] FIXME all the technical work required to make the CUE docs match this discussion. For example, CLI updates - https://github.com/dagger/dagger/discussions/3432#discussioncomment-3917550 @samalba @gerhard need help here to coordinate the technical requirements and release requirements 

## Architecture

```mermaid
graph TD;

tl["Top-level docs"]
go["Go SDK docs"]
cue["CUE SDK docs"]

tl --> go & cue
```

### 1. Click on docs.dagger.io 

Sees a single site that includes the following: 
- Introduction to Dagger Overview Page and a sidebar
- FAQ

Sidebar has the following: 
- Go SDK button to push to a Go SDK microsite with it's own sidebar 
- CUE SDK button that pushes to old Dagger Docs that are relevant with it's own side bar

### 2. When clicking one of the SDKs in the sidebar: 
- You go to SDK-specific docs site 
- Search only shows you that specific SDK documentation 
- There is a docs home button on the top of the sidebar to easily get back to the main docs site if you'd like.

**Comment by mircubed** [comment]
wonder if we need to change anything for anlaytics based on this PR and the updated plan @slumbering @gerhard https://github.com/dagger/dagger/pull/3434

**Comment by slumbering** [comment]
> wonder if we need to change anything for anlaytics based on this PR and the updated plan @slumbering @gerhard #3434

Yes, my PR was targeting docs.dagger.io and not the GO SDK microsite. Because it has been merged, the project Docs-0.3 within Posthog should be deleted and recreated to get a new API token and used into the microsite.

**Comment by vikram-dagger** [comment]
I think we can close this issue. WDYT @mircubed ?
