### ISSUE TITLE
Release CUE SDK

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#3445]
## Overview

This issue tracks the release of a new CUE SDK, which is the evolution and replacement of the original dagger 0.2 engine and tool, aka "dagger classic".

This issue should be closed when the first version of the CUE SDK is available and usable by users end-to-end. *It does not include launch work*: the work to make this SDK visible from our landing page, stable docs etc. is out of scope.

For more context, and ongoing debates on implementation, see https://github.com/dagger/dagger/discussions/3432

## Task list

- [x] Choose a new name for the dagger classic CLI. See https://github.com/dagger/dagger/discussions/3432 for ongoing discussion (@shykes ) DONE: the name is `dagger-cue`
- [x] #3471
- [ ] Track down all downstream consequences of of the binary name change, and resolve them: https://github.com/dagger/dagger/issues/3447 (@jpadams )
- [ ] #3470
- [ ] Define the tagging, versioning and releasing strategy for the new *dagger-cue* CLI (@jpadams made a list, but need to confirm if @gerhard is owning the completion?) https://github.com/dagger/dagger/issues/3447
- [ ] Cut a first release of the *dagger-cue* CLI to make sure everything works (@gerhard ??)
- [x] Transpose the contents of the 0.2 docs into a new "Dagger CUE SDK" site, with all suitable changes made (see next section) (@jpadams ) https://github.com/dagger/dagger/issues/3474
- [ ] Merge all of the above, end-to-end testing on devel.docs.dagger.io

## End result

The CUE SDK is fully released, but not yet launched.

## CUE SDK docs change

From the current dagger 0.2 docs, the following changes are needed to produce the new Dagger CUE SDK docs:

* Rename binary from `dagger` to the new name: `dagger-cue`
* Update install instructions to match new release strategy
* Remove articles that contradict the new branding as "just a CUE SDK".
* Remove top-level content like introductions, etc
* FAQ to address "My `dagger` 0.2 pipleline/cli broke..."
* ?

**Comment by mircubed** [comment]
closing since most of these tasks are complete.
