### ISSUE TITLE
🐞 codegen: Handling lists of objects

### ISSUE THREAD

**Issue by helderco** [dagger/dagger#3457]
## Overview

The Go generated client executes the query when a scalar or list is requested.

https://github.com/dagger/dagger/blob/fdbf190307776b4cfb8acaa39cc82956d104e310/codegen/generator/templates/src/object.go.tmpl#L40-L44

## Problem

When it's a list of objects you need to select the fields.

I looked the API for a problematic case:

```graphql
type Container {
  envVariables: [EnvVariable!]!
}

type EnvVariable {
  name: String!
  value: String!
}
```

In fact when attempting to call it:

```diff
diff --git a/sdk/go/dagger/client_test.go b/sdk/go/dagger/client_test.go
index bd5fbefd..74263ae0 100644
--- a/sdk/go/dagger/client_test.go
+++ b/sdk/go/dagger/client_test.go
@@ -101,3 +101,23 @@ func TestContainer(t *testing.T) {
        require.NoError(t, err)
        require.Equal(t, "3.16.2\n", contents)
 }
+
+func TestList(t *testing.T) {
+       t.Parallel()
+
+       ctx := context.Background()
+
+       c, err := Connect(ctx)
+       require.NoError(t, err)
+       defer c.Close()
+
+       alpine := c.
+               Core().
+               Container().
+               From("alpine:3.16.2")
+
+       envs, err := alpine.EnvVariables(ctx)
+
+       require.NoError(t, err)
+       require.Equal(t, "PATH", envs[0].Name)
+}
```

I get an error:

```
Error: Received unexpected error:
       input:1: Field "envVariables" of type "[EnvVariable!]!" must have a sub selection.
```

/cc @aluzzardi @dolanor 
```[tasklist]
### Tasks
- [x] https://github.com/dagger/dagger/pull/4683
- [x] https://github.com/dagger/dagger/pull/5375
- [x] https://github.com/dagger/dagger/pull/5523
```

**Comment by aluzzardi** [comment]
@sipsma's suggestion in #3860

> RE: how we can fix this. @aluzzardi mentioned not allowing objects in lists in Discord (at least that was my understanding, correct me if wrong).
> 

Yeah, basically a workaround so it stops hurting. Of course with extensions the pain will come back at some point.

> If we are willing to trade more complexity for having the ability to return objects in lists maybe we could figure something out around autoselecting all trivial scalars for those cases, though I don't know if we'll have to apply that fix on a case-by-case basis (ugly) or if there's a way of cleanly generalizing it. Vague idea, might be a deadend, but in general it would be nice to support these return types.

Agreed. This might be the cleanest solution, although I'm not sure either about edge cases.

Also creates a disparity between `Object` (need to call `Object.Field(ctx)` -- it's lazy) and `[Object!]!` (need to call `Object.Field` -- it's not lazy). We could have both APIs be the same, but the behavior would be different (lazy vs non-lazy) which can be confusing. Implementation would also need to be different (return "pre-fetched" field vs query the API).

There's also a half-baked option which is auto-selecting `ID` to make the query work, keeping leaf resolvers as usual. The problem though is how to "resume the query" (when calling `.Field(ctx)`). Either we re-run the full query with the extra field (but there's no way in GraphQL to select the Nth element, so we'd be calling `field` on ALL elements) OR we find a different way to resume the query (top-level selector ... but that's very manual)

**Comment by vito** [comment]
A similar issue came up when I was implementing `Stat` (#3764). The GraphQL interface is something like `Directory { stat(path: String): FileInfo! }` with `FileInfo` being a type sort of like [`fs.FileInfo`](https://pkg.go.dev/io/fs#FileInfo). But right now you actually have to select each individual field like `size, err := dir.Stat().Size(ctx)`.

It's not the exact same problem, but maybe our solution here could address both.

**Comment by helderco** [comment]
Somewhat related:
- https://github.com/dagger/dagger/issues/3577

**Comment by TomChv** [comment]
Reopen because it's not implemented for NodeSDK and Python for now

**Comment by gerhard** [comment]
What should happen next with this? Were any PRs opened for this?

**Comment by helderco** [comment]
It's been fixed in Go, needs fixes for Node.js and Python.

This proposal suggests a different implementation:
- #4920 

But in the meantime I'll do the same that was done in Go, maybe @TomChv can work on the Node.js fix.

**Comment by helderco** [comment]
Python fix has been merged. Only Node.js remaining.

**Comment by gerhard** [comment]
OK!

We want to get a new release out this week, which leaves us with today.

Would delaying it by a few more hours make a difference for Node.js?

**Comment by helderco** [comment]
That depends on @TomChv, but probably not enough time.

**Comment by gerhard** [comment]
Not a problem, it's OK to leave it for the next release. 👍 @TomChv

**Comment by helderco** [comment]
As early as @TomChv can do it. 👍
