### ISSUE TITLE
Add Python's CI pipeline to mage

### ISSUE THREAD

**Issue by helderco** [dagger/dagger#3678]
Depends on:
- #3672
- #3720
- #3730

## Tasks

- [x] Add **generate** step
  - [x] Need to `lint:fmt` afterwards
- [x] Add **lint** (`lint:style`) step
- [x] Add **publish** with *build*

\cc @aluzzardi

**Comment by gerhard** [comment]
Discussed sync with @helderco, he will add the **build** & **deploy** examples and then I can take it from there.

**Comment by aluzzardi** [comment]
Relevant: #3704

- `sdk:python:lint` --> implemented
- `sdk:python:generate` --> implemented
- `sdk:python:test` --> implemented
- `sdk:python:publish <version>` (??) --> this issue

**Comment by helderco** [comment]
For publish the bones are in:
- #3720

**Comment by helderco** [comment]
Implemented here:
- https://github.com/dagger/dagger/pull/3730
