### ISSUE TITLE
Add Python's CI pipeline to GitHub Actions

### ISSUE THREAD

**Issue by helderco** [dagger/dagger#3682]
## Tasks

- [x] Add steps from #3678
  - [x] Deploy (trigger on release)
- [x] Add test step (trigger on PRs)

\cc @gerhard

**Comment by helderco** [comment]
Here's an example of building wheels for mac, linux and windows as well as publishing with hatch: https://github.com/ofek/hatch-showcase/blob/master/.github/workflows/build.yml

**Comment by helderco** [comment]
Copied the GHA to publish from go here https://github.com/dagger/dagger/pull/3730
