### ISSUE TITLE
Fix engine provisioning

### ISSUE THREAD

**Issue by helderco** [dagger/dagger#3686]
Depends on:
- https://github.com/dagger/dagger/issues/3653

## Todo

- [x] Use a worker thread with sync code[^1]
- [x] Follow instructions in https://github.com/dagger/dagger/issues/3653#issuecomment-1303984783
- [x] Use `docker.io/eriksipsma/test-dagger@sha256:eb6a15a52fed7ac51b26e181dc1c6b2731ba0451f1951c575d85690159cb0722`
- [ ] Test connection

[^1]: Quicker to reuse previous sync implementation and to have it ready for sync support.
