### ISSUE TITLE
Python: Run auto provisioning in async

### ISSUE THREAD

**Issue by helderco** [dagger/dagger#3687]
The auto provisioning (having the SDK launch the engine session in a subprocess automatically, including downloading the CLI if on in the default cache dir) is being done in sync (in a worker thread). Make it run in async instead.

```[tasklist]
### Tasks
- [ ] Non-blocking
- [ ] Info and debug logs during provisioning
- [ ] Include stderr in provisioning error when `log_output` is set
- [ ] Make sure cancellations are properly handled and work as expected
- [ ] Make sure timeouts are properly handled during connection, not just query execution
- [ ] Consider supporting retries on a failed connection
- [ ] Capture more error conditions
- [ ] Capture OS signals to shut down
```

### Related
- https://github.com/dagger/dagger/issues/3806
- https://github.com/dagger/dagger/issues/3838

**Comment by helderco** [comment]
I'm closing this in favor of shifting to using modules which don't need provisioning. The current sync approach is good enough in the meantime.
