### ISSUE TITLE
Migrate to httpx

### ISSUE THREAD

**Issue by helderco** [dagger/dagger#3693]
## Reasons

- Supports [AnyIO](https://anyio.readthedocs.io/en/stable/), which supports both [asyncio](https://docs.python.org/3/library/asyncio.html) (built-in) and [Trio](https://github.com/python-trio/trio) (easier to use);
- Supports both async and sync (currently we're using [aiohttp](https://docs.aiohttp.org) for one and [requests](https://requests.readthedocs.io/en/latest/) for the other);
- Simpler support for unix socket connections (https://github.com/dagger/dagger/issues/3694);

## Todo

- [x] Create _async_ transport for GraphQL client
- [x] Create _sync_ transport for GraphQL client
- [x] Hook them in dagger's `HTTPConnector`
- [x] Sunset _aiohttp_

**Comment by helderco** [comment]
Draft implementation:
- https://github.com/graphql-python/gql/pull/340

**Comment by helderco** [comment]
That draft is a bit stuck, I'm planning on contributing this upstream.

**Comment by helderco** [comment]
Upstream contribution:
- https://github.com/graphql-python/gql/pull/370

**Comment by helderco** [comment]
This migration and the latest changes to provisioning made it clear that the current architecture isn't the best one.

- The point of the current architecture was to allow for multiple ways to connect to the engine that I was seeing at the time: _http_, _unix socket_, _dial stdio_, _bin_;
- Current dispatch based on `DAGGER_HOST` scheme is essentially only used for provisioning, so rename the `connectors` package to `provision`;
- Move `HTTPConnector` specific code to `Connector` and move `connectors.base` to `connection`.
- With only _httpx_ for sync/async, we can [mount _httpx_ transports](https://www.python-httpx.org/advanced/#mounting-transports) for unix sockets for example, and not do the dispatch ourselves.
