### ISSUE TITLE
Make library fully type correct

### ISSUE THREAD

**Issue by helderco** [dagger/dagger#3701]
## Todo
- [ ] No mypy warnings[^1]
- [ ] Support Pyright (Microsoft's type checker, default in VS Code)
- [ ] Add to lint step for CI (`lint:typing`)

[^1]: The ones that are leftover represent some annoyances, and don't suggest any bug. I decided to move on to not waste time for now.

**Comment by helderco** [comment]
I'm hoping to chip away mypy errors bit by bit over time, instead of focusing all attention on this.
