### ISSUE TITLE
Codegen: Support chainable utils via `With(...)`

### ISSUE THREAD

**Issue by sipsma** [dagger/dagger#3885]
A current pain point of our SDKs is that any time you want to write your own util that's not in our API, it has to "break the chain".

e.g.
```go
func AddAFewMounts(c *dagger.Container) *dagger.Container {
  return c.
    WithMountedDirectory("/foo", c.Host().Directory("foo").
    WithMountedDirectory("/bar", c.Host().Directory("bar")
}

func main() {
 ctr := Container().
    From("alpine").
    WithWorkdir("/foo")
ctr = AddAFewMounts(ctr) // The chain is broken!!!!!!
output, err := ctr.Exec("blah").Stdout().Contents()
...
}
```

This isn't a huge deal but can get more annoying the more modular utils you want to write.

Instead, we could have our codegen clients include a `.With(...)` method on chainable objects that could be used like this:
```go
func AddAFewMounts(c *dagger.Container) *dagger.Container {
  return c.
    WithMountedDirectory("/foo", c.Host().Directory("foo").
    WithMountedDirectory("/bar", c.Host().Directory("bar")
}

func main() {
 output, err := Container().
    From("alpine").
    WithWorkdir("/foo").
    With(AddAFewMounts).
    Exec("blah").Stdout().Contents()
...
}
```

In Go, `With` could have signatures like:
```go
func (c *Container) With(f func(*Container)) *Container {
  return f(c)
}
...
func (d *Directory) With(f func(*Directory)) *Directory {
  return f(d)
}
```

I imagine similar signatures could be generated for our other SDKs (?)

I think this would be a small-to-medium size improvement to DX and may be an interesting place for future extensions to integrate (maybe).

```[tasklist]
### Todos
- [x] https://github.com/dagger/dagger/pull/4332
- [x] https://github.com/dagger/dagger/pull/4898
- [x] https://github.com/dagger/dagger/pull/4922
- [ ] Apply to a subset of types [selectively](https://github.com/dagger/dagger/issues/3885#issuecomment-1502081027)
- [ ] Standardize *docstrings*
- [ ] Maybe standardize tests
- [ ] https://github.com/dagger/dagger/issues/5236
```

**Comment by helderco** [comment]
I like that. I want to experiment with that pattern.

**Comment by aluzzardi** [comment]
I like it!

Maybe it's too complex, but a more powerful thing would be to follow the `http.Handler` middleware pattern and return a callback. This would allow to parameterize the `With()` statement:

```go
func InstallAFewPackages(pkg ...string) WithContainerFunc {
  return func(c *dagger.Container) *dagger.Container {
    for _, p := range pkg {
      c = c.Exec("apk", "add", p)
    }
    return c
  }
}

func main() {
 output, err := Container().
    From("alpine").
    WithWorkdir("/foo").
    With(InstallAFewPackages("bash", "curl", "jq")).
    Exec("blah").Stdout().Contents()
...
}
```

**Comment by helderco** [comment]
Just saw https://github.com/dagger/dagger/pull/4173 and immediately thought of this.

## Before

```go
	memcached := client.Container().
 		From("alpine:3.17").
 		WithExec([]string{"addgroup", "-g", "11211", "memcache"}).
 		WithExec([]string{"adduser", "-D", "-u", "1121", "-G", "memcache", "memcache"}).
 		WithExec([]string{"apk", "add", "--no-cache", "libsasl"}).
 		WithEnvVariable("MEMCACHED_VERSION", "1.6.17").
 		WithEnvVariable("MEMCACHED_SHA1", "e25639473e15f1bd9516b915fb7e03ab8209030f")

 	// add dependencies to the container
 	memcached = setDependencies(memcached)

 	// add source code to the container
 	memcached = downloadMemcached(memcached)

 	// build the application
 	memcached = buildMemcached(memcached)

 	// set the container entrypoint
 	entrypoint := client.Host().Directory(".").File("docker-entrypoint.sh")
 	memcached = memcached.
 		WithFile("/usr/local/bin/docker-entrypoint.sh", entrypoint).
 		WithExec([]string{"ln", "-s", "usr/local/bin/docker-entrypoint.sh", "/entrypoint.sh"}).
 		WithEntrypoint([]string{"docker-entrypoint.sh"}).
 		WithUser("memcache")

 	// publish the container image
 	addr, err := memcached.Publish(ctx, publishAddr)
```

## After

```go
 	entrypoint := client.Host().Directory(".").File("docker-entrypoint.sh")

	memcached := client.Container().
 		From("alpine:3.17").
 		WithExec([]string{"addgroup", "-g", "11211", "memcache"}).
 		WithExec([]string{"adduser", "-D", "-u", "1121", "-G", "memcache", "memcache"}).
 		WithExec([]string{"apk", "add", "--no-cache", "libsasl"}).
 		WithEnvVariable("MEMCACHED_VERSION", "1.6.17").
 		WithEnvVariable("MEMCACHED_SHA1", "e25639473e15f1bd9516b915fb7e03ab8209030f").
 		With(setDependencies).
 		With(downloadMemcached).
 		With(buildMemcached).
 		WithFile("/usr/local/bin/docker-entrypoint.sh", entrypoint).
 		WithExec([]string{"ln", "-s", "usr/local/bin/docker-entrypoint.sh", "/entrypoint.sh"}).
 		WithEntrypoint([]string{"docker-entrypoint.sh"}).
 		WithUser("memcache")

 	// publish the container image
 	addr, err := memcached.Publish(ctx, publishAddr)
```

**Comment by slumbering** [comment]
Is this implemented in Python @helderco ?

**Comment by helderco** [comment]
No, but I want to 😍

**Comment by slumbering** [comment]
Yes me too 😍

**Comment by slumbering** [comment]
PR opened for Node.js SDK:
- #4332

**Comment by helderco** [comment]
Looking at this and I see two changes.

## Need to pass the client

When you call `c.Host()...`, you mean to call this on the _client_ (i.e., root `Query`), not `Container`. So I think these functions need 2 arguments: the current instance and the client.

```go
func AddAFewMounts(ctr *dagger.Container, client *dagger.Client) *dagger.Container {
  return ctr.
    WithMountedDirectory("/foo", client.Host().Directory("foo").
    WithMountedDirectory("/bar", client.Host().Directory("bar")
}
```

## Why not return other types?

Instead of only returning the same type, why not allow any type to be returned? For example, `Container.Directory` returns a `dagger.Directory`, this would allow more flexibility. 

This can be solved with generics. Here's Python's implementation, doesn't even have to be codegen'ed:

```python
class Type(Object):
    def with_(self, cb: Callable[[Self, Root], T]) -> T:
        return cb(self)
```

**Comment by gerhard** [comment]
@vito just mentioned this, and this is exactly what I kind of implemented in a different way here, using `Build`: https://github.com/thechangelog/changelog.com/blob/77cd98383a165ff3053c893fc719f4ea8486e605/magefiles/image/image.go#L95-L105 .

That allows me to do things like:

```go
	build.
		Elixir().
		WithAptPackages().
		WithGit().
		WithImagemagick().
		WithCmarkPrerequisites().
		WithInotifyTools().
		WithPostgreSQLClient().
		WithNodejs().
		WithYarn().
		OK().
		Publish()
```

Definitely want 🙏

**Comment by helderco** [comment]
Taking another look at this and I'm (still) wondering about passing the client. **Requesting a consensus here**, to move this forward.

## Option 1: Use factory

```go
func AddAFewMounts(client *dagger.Client) WithContainerFunc {
  return func(c *dagger.Container) *dagger.Container {
    return ctr.
      WithMountedDirectory("/foo", client.Host().Directory("foo")).
      WithMountedDirectory("/bar", client.Host().Directory("bar"))
  }
}
```

Downside is perhaps unnecessarily verbose for such a common need (accessing the client). It's also not intuitive so we need to teach this pattern. In Python there's no anonymous functions (only single statements) so you need a little more boilerplate if you do it often.

Seems like this pattern should be considered "advanced" usage.

## Option 2: Always pass in client

```go
func AddAFewMounts(c *dagger.Container, client *dagger.Client) *dagger.Container {
  return c.
    WithMountedDirectory("/foo", client.Host().Directory("foo")).
    WithMountedDirectory("/bar", client.Host().Directory("bar"))
}
```

Question is, is it common enough to justify always passing the client? Downside is sometimes you don't need it so you have to ignore it:

```go
func AddEnvs(c *dagger.Container, _ *dagger.Client) *dagger.Container {
  return c.
    WithEnvVariable("GOOS", "darwin").
    WithEnvVariable("GOARCH", "arm64")
}
```

## Option 3: Access client from any type

```go
func AddAFewMounts(c *dagger.Container) *dagger.Container {
  client := c.Client()
  return c.
    WithMountedDirectory("/foo", client.Host().Directory("foo")).
    WithMountedDirectory("/bar", client.Host().Directory("bar"))
}
```

Best of both worlds? Simple function signature while all types having easy access to the root `Client` instance avoids the need to pass it explicitly as we need to now.

@aluzzardi @shykes for feedback

**Comment by aluzzardi** [comment]
Not very strong opinion, but IMHO option 1 makes the most sense.

Passing the client is a special case of passing *something*. I think that's going to be pretty common. For instance, you could write `AddAFewMounts` like this:

```go
func AddAFewMounts(map[string]*dagger.Directory mounts) WithContainerFunc {
  return func(c *dagger.Container) *dagger.Container {
    for mntpoint, dir := range mounts {
      c = c.WithMountedDirectory(mntpoint, dir)
    }
    return c
  }
}
```

Gut feeling is needing the client is not more common than needing "something". And if it turns out to be wrong, Option 3 is still be available.

Thoughts?

/cc @shykes @sipsma

**Comment by helderco** [comment]
> Gut feeling is needing the client is not more common than needing "something".

Yeah, that was the main thing I was wondering about. I think you're right. In the guide I referenced in https://github.com/dagger/dagger/issues/3885#issuecomment-1372712740 above, those functions don't need client. 

So it doesn't seem like _option 2_ is justifiable. Let's scratch that and **follow the original proposal to get this in Go and Python**.

There's two new follow-up issues I'll create:
- NodeJS needs to update the examples to use the pattern in _option 1_ instead of getting client via `new Client()` as shown in https://github.com/dagger/dagger/issues/4835#issuecomment-1488563345
- Support convenience of _option 3_

**Comment by jlongtine** [comment]
@helderco Just dropping a note to say that I'd love to have this pattern in my refactor of `internal/mage`. There are a few bits of code that would be much nicer with this pattern.

**Comment by sipsma** [comment]
> Just checking that whatever option we choose, it’s forward-compatible (as far as we know) with extensions and the composition model that they will enable?

Yeah obviously it's fuzzy but I can see several ways this could easily integrate with extensions. The base idea would be to take functions with signatures matching a `With` callback and make those invokable from our SDKs. This would re-use all the same mechanics of more general extension support. Two possible approaches:

1. Without extra client codegen - users call something like 
```go
c.Container().With(c.ContainerExtension("github.com/foo/bar", "AddAFewMounts"))
```
   * `ContainerExtension` is a bit verbose, but can bikeshed that later

2. With extra client codegen - generate a function like:
```go
func AddAFewMounts(ctr *Container) *Container {
  return ctr.With(ContainerExtension("github.com/foo/bar", "AddAFewMounts"))
}
```

**Comment by shykes** [comment]
@sipsma is there an option 3 where my util could in the future be mapped to its own graphql resolver, and added to the GraphQL schema as a full-blown step - from which codegen could then generate native chain steps?

**Comment by sipsma** [comment]
> is there an option 3 where my util could in the future be mapped to its own graphql resolver, and added to the GraphQL schema as a full-blown step - from which codegen could then generate native chain steps?

Depends on exactly what you mean, especially in terms of "generate native chain steps".

If you just mean being able to generate an SDK that has the util baked in like `ctr.AddAFewMounts()`, then yes that would be totally possible. This would actually solve an open question with the current extension implementation where support for extending types from core or other extensions isn't possible, you can only define your own types+methods (due to restrictions in the type systems of languages like Go). Our solution to supporting `With` utils here would be our solution to that problem too.

If by "generate native chain steps", you mean that we'd be able to convert the actual implementation of a util func from one language to another, then no I don't think that's feasible in general. If we arbitrarily limited the utils to be very simple chains of method calls, then maybe, but that would rule out using loops, conditionals, libraries, etc. That would feel like a big restriction without much benefit.

**Comment by TomChv** [comment]
> NodeJS needs to update the examples to use the pattern in option 1 instead of getting client via new Client() as shown in https://github.com/dagger/dagger/issues/4835#issuecomment-1488563345

I'm not sure I understand what you mean. I added additional patterns in #4907 tov verify it works according to #4898 tests.

**Comment by helderco** [comment]
> > NodeJS needs to update the examples to use the pattern in option 1 instead of getting client via new Client() as shown in [#4835 (comment)](https://github.com/dagger/dagger/issues/4835#issuecomment-1488563345)
> 
> I'm not sure I understand what you mean. I added additional patterns in #4907 to verify it works according to #4898 tests.

I mean this:

https://github.com/dagger/dagger/blob/ff7653d0dd6e2bb50243f05b57a3d5d57fad1a92/codegen/generator/nodejs/templates/src/object.ts.gtpl#L42-L46

I suggest two examples: a simple one without any external dependencies, and a second one with the example above but using a factory function.

There's also the following test:

https://github.com/dagger/dagger/blob/ff7653d0dd6e2bb50243f05b57a3d5d57fad1a92/sdk/nodejs/api/test/api.spec.ts#L220-L224

**Comment by helderco** [comment]
NodeJS has an implementation and Go implementation has [been submitted](https://github.com/dagger/dagger/pull/4898), so I'm going to make a quick Python implementation as well.

Self-assigning to push this forward and syncing between SDKs.

**Comment by helderco** [comment]
## SDK implementations

- [x] https://github.com/dagger/dagger/pull/4332
- [ ] https://github.com/dagger/dagger/pull/4898
- [ ] https://github.com/dagger/dagger/pull/4922

## Drift: apply to which objects?

NodeJS first implemented using codegen, on all object types. However, in the Go implementation, @jlongtine is applying only to `Container` and `Directory`. He raised the question "What do you imagine doing with `func (c *CacheVolume).With(...) *CacheVolume`? He has a point 🤔

However, I prefer either applying to all types or finding some rule to be more selective, but I'd rather not manually hardcode which ones to select. Otherwise, if a new type comes along where this could be useful, someone has to remember to add that type to the list.

I submitted a proposal to [return simple objects](https://github.com/dagger/dagger/issues/4920) in codegen. That requires codegen to tell the difference between a plain object (e.g., `EnvVariable`, `Port`, `Label`) and a normal object type like `Container` and `Directory`. If in addition we exclude `ID()` and deprecated fields, selecting only the non-empty objects that are left, already excludes `EnvVariable`, `Port`, `Label`, `CacheVolume`, `Socket`, etc.

So the Python implementation is not using codegen (for now), but has a general implementation in the base type. If the [return simple objects](https://github.com/dagger/dagger/issues/4920) proposal gets accepted, that implementation will automatically change the base class for these objects, thus not including `with_()` in these cases.

In the meantime, we can also do a **follow up to implement this detection in all SDKs, fixing this drift**, while also solving the first step of that proposal. I don’t think it’s necessary to hold on merging the current PRs waiting for this though.

**Comment by helderco** [comment]
All SDKs have an implementation, but there’s a slight drift:
- [ ] Apply to a subset of types selectively: more context in my previous comment
- [ ] Standardize *docstrings*
- [ ] Maybe standardize tests

After these tasks, this issue can be closed.

**Comment by helderco** [comment]
I found a better rule for selectively choosing which types to add this method: object types that have at least one field that returns the current type. I'll submit a PR soon that'll close this issue.
