### ISSUE TITLE
Python: Simplify provisioning the engine

### ISSUE THREAD

**Issue by helderco** [dagger/dagger#4210]
## Overview

Follow up to:
- https://github.com/dagger/dagger/pull/4145
- https://github.com/dagger/dagger/pull/4194
- https://github.com/dagger/dagger/pull/4208

Related:
- https://github.com/dagger/dagger/issues/3830

With the recent changes to provisioning and the intent to simplify things, the current architecture in the Python SDK can use some simplification as well.

## Tasks

- [x] Abandon `DAGGER_HOST` based registration system
    - [x] Move connection parameters from `dagger.Config` into internal object (`host` and `secret_token`, should not be configured by user, only via env vars)
    - [x] Refactor `bin.Engine` and `bin.DownloadBinEngine` as utility classes instead 
    - [x] Use `dagger.engine.Engine` as single dispatcher
        - Try `DAGGER_SESSION_URL` first
        - If `_EXPERIMENTAL_DAGGER_CLI_BIN` isn’t set, download CLI
        - Run engine session
    - [x] Avoid `start`/`connect` methods and just use `__enter__`
- [x] Rename `Connector` → `Session`
- [x] Move `_version.py` → `engine/_version.py`
- [x] Separation of concerns for `Session` (just return GraphQL session and create `dagger.Client` instance in `Connection` instead)
    - [x] Simplify codegen
- [x] Move all custom exceptions in to `dagger.exceptions`
- [x] Make code easier to test to avoid monkey patching
- [x] Use `ExitStack` for proper cleanup since we use a lot of context managers (resolves a few FIXMEs)
- [x] Leverage *httpx* instead of using lower level libraries
    - [x] Simplify download logic
    - [x] Stream responses instead of loading into memory
    - [x] Extract from zip archive (windows)
    - [x] Simplify error handling when running CLI session
- [x] Fix tests
    - [x] Create zip archive (windows)
- [x] Check mypy
- [ ] Add logging statements
- [ ] Maybe on bin error, compare version and see if it’s lower than `CLI_VERSION`? 🤷
