### ISSUE TITLE
engine: `dagger session` error messages lack context

### ISSUE THREAD

**Issue by grouville** [dagger/dagger#4320]
### Context

When running any of the SDKs (apart the Go one), whenever a `session` error gets triggered, output error messages are hard to decipher, leaving users with no actionable setps to debug, except requesting more information on Discord.

Current cases:
- the user manually stops his engine container
- the user is referencing a wrong engine, with its environment variables

Currently, the only error feedback retrieved is a hardcoded `buildkit failed to respond` message, either retrieved by SDKs, or similar hardcoded string.

### Solution

@sipsma suggested that we [forward the stdout + stderr](https://github.com/dagger/dagger/pull/4284) of our connection to Buildkit. This error message would then be forwarded by SDKs to end users.

### Sub-issues

All the steps required to fully solve to the inherent DX mismatch:
- [x] https://github.com/dagger/dagger/pull/4303 
- [x] https://github.com/dagger/dagger/pull/4284

Next steps (to be resolved by SDK owners, or conjointly with them):
- [x] https://github.com/dagger/dagger/issues/4321
- [x] https://github.com/dagger/dagger/issues/4322

**Comment by grouville** [comment]
Closed, as SDKs now have unified error message management 🚢
