### ISSUE TITLE
Python: Update reference docs

### ISSUE THREAD

**Issue by helderco** [dagger/dagger#4704]
```[tasklist]
### Tasks
- [ ] #4703
- [ ] #4685
- [x] Autodoc from `__init__`?
- [ ] Add link to Conda package
- [ ] Expose (public) inherited members like `with_`
```

**Comment by helderco** [comment]
Just an update: I started working on this a month ago but it was harder than it looks and had to shift focus to other priorities.
