### ISSUE TITLE
📖 Python entrypoint example/guide

### ISSUE THREAD

**Issue by helderco** [dagger/dagger#4707]
Most of our examples are for simple scripts. Larger pipelines benefit from a different project organization.

```[tasklist]
### Tasks
- [ ] Executable with sub-commands matching pipelines
- [ ] Showcase concurrency with "all" sub-command
- [ ] Showcase setting `pipeline`
- [ ] Showcase rich progress status
- [ ] Showcase error handling (capture exceptions) with logging
- [ ] Pattern for encapsulating a "workflow job" (OOP?), with name/description, result report, etc
```

**Comment by helderco** [comment]
@cpdeethree this is what I was talking about the other day. I had it on my list since the end of last year but only created the issue after https://github.com/airbytehq/airbyte/pull/23487.

I'll close in favor of the new [project commands](https://github.com/dagger/dagger/pull/5300).
