### ISSUE TITLE
PHP SDK: Get Short and Long Descriptions of Module

### ISSUE THREAD

**Issue by charjr** [dagger/dagger#8495]
On the daggerverse modules can have [long and short descriptions.](https://daggerverse.dev/mod/github.com/levlaz/daggerverse/docusaurus).

[PHP SDK Modules do not currently support this.](https://daggerverse.dev/mod/github.com/dagger/dagger/sdk/php/dev)

### Tasks
- [ ] Add `ValueObject\DaggerJsonFile`
  - has`name` property, should be the name of the module.
  - has `getBaseClassName` method, should return the expected name of the base class. 
- [ ] Add `Service\FindsDaggerJsonFile`. 
  - has `getDaggerJsonFile` method: finds the `dagger.json` file and returns contents as `ValueObject\DaggerJsonFile`.
  - has `getDaggerJsonFilepath` finds the `dagger.json` file and returns filepath.
- [ ] Refactor `Service\FindsSrcDirectory` to make use of `FindsDaggerJsonFile`
- [ ] Refactor `Service\FindsDaggerObjects` to identify the base class using `ValueObject\DaggerJsonFile::getBaseClassName`
  - This may require adding a bool property to `ValueObject\DaggerObject` `$isBaseClass`

- [ ] Either reuse the `#[Description] Attribute or add a new Attribute `#[Description(string $description)]` which will be ignored on anything other than the base class.
